### ISSUE TITLE
Search page bugs

### ISSUE THREAD

**Issue by itechify** [autoinvent/conveyor#152]
https://github.com/autoinvent/conveyor/blob/184604261996fad91d6de1cf40ac43fc885058ea/src/Search.tsx#L106
This makes too many assumptions about the path. Also wouldn't work properly if `/` is included in the search term. Initially I would think this could be fixed by getting the _last_ item in the array, but the `/` would screw this up. Probably should use react-router variable instead of the path directly. ie:
```
<Route path="/users/:id" render={(props) => <UserPage {...props} />}/> 
this.props.match.params.id
```

https://github.com/autoinvent/conveyor/blob/184604261996fad91d6de1cf40ac43fc885058ea/src/Search.tsx#L160
Should get the display name for the model instead of using the model name directly. conveyor-schema has a method for getting the plural model label: https://github.com/autoinvent/conveyor-schema/blob/b5c0b441ee3678c2085566f44bf1f800839cf2d4/src/schemaBuilder.ts#L212-L227

**Comment by apastel** [comment]
Adding onto search page bugs:

1. Search filter boxes are styled such that if the window minimizes, the checkboxes and counts get bumped to another row
![search_filters](https://user-images.githubusercontent.com/8836343/124964207-f9fff600-dfdd-11eb-8b5c-7c017d01489f.gif)

2. Search string says "4 results found for "Search"" instead of what the actual query was
![image](https://user-images.githubusercontent.com/8836343/124964837-b5288f00-dfde-11eb-8125-3234bb30514c.png)

**Comment by DanielHall977** [comment]
This PR may address itechify's original concern:  https://github.com/autoinvent/conveyor/pull/155

**Comment by DanielHall977** [comment]
Branches are merged, this should be done.

If there are more bugs left they should be done with individual issues.
